<?php

namespace SurveyBundle\Repository;

/**
 * PreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
