<?php

namespace SurveyBundle\Repository;

/**
 * RespuestaEncuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestaEncuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
