<?php

namespace SurveyBundle\Repository;

/**
 * RespuestaElegidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestaElegidaRepository extends \Doctrine\ORM\EntityRepository
{
}
